### PR TITLE
fix(slow-query): sometimes, two queries are better than one.

### LINKED ISSUE #48: SQL Issue
Hey everyone.

I got a lot of warning from the DB coming from QB-crypto while trying to update value. I'm using an API to have the real price of Bitcoin on my city and also add an update when ressources start into.

Every time it update I got this warning is this normal or need to be optimize in some way ? I have updated my oxmysql for the lastest version.

### PR DESCRIPTION
**Pull request by MatthewRorke**
**Describe Pull request**
Resolves #48 

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes (Be honest)
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

File: server/main.lua [hunk 1]
```diff
@@ -86,11 +86,23 @@ local function HandlePriceChance()
...
+    local history = json.encode(Crypto.History[coin])
+    local props = {
         ['worth'] = currentValue,
-        ['history'] = json.encode(Crypto.History[coin]),
-    })
-    RefreshCrypto()
+        ['history'] = history,
+        ['crypto'] = coin
+    }
+    MySQL.Async.execute(
```
Comment (BerkieBb) [inline server/main.lua:95]: Use `MySQL.update` instead

**Review by BerkieBb — CHANGES_REQUESTED** [review]

**Review by BerkieBb — APPROVED** [review]
